name: CheckAndDeploy

on:
  schedule:
    - cron: "0 */4 * * *" # run every 4 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  checkAndDeploy:
    runs-on: ubuntu-22.04
    steps:
      - name: check repos
        uses: malaupa/composite-apt-repo-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repositories: |
            telekom-mms/fw-id-agent
            telekom-mms/oc-daemon
            telekom-mms/corp-net-indicator
          target_os_release: |
            jammy
          repo_supported_arch: |
            amd64
          repo_supported_version: |
            jammy
          public_key: ${{ secrets.PUB_KEY }}
          private_key: ${{ secrets.PRV_KEY }}
          key_passphrase: ${{ secrets.PASS_PHRASE }}
